### ISSUE TITLE
Import not found: `kirbyStatic`

### ISSUE THREAD

**Issue by antoine3000** [johannschopplich/cacao-kit-frontend#5] opened 2024-05-12 14:20 UTC
Hey!

The app doesn't work on Firefox, because of an import not found. On Chrome it works.

`Uncaught SyntaxError: import not found: kirbyStatic [page.ts:3:9](http://localhost:3000/_nuxt/composables/page.ts)`

Any idea on how to fix it?
Thanks!

**Comment by johannschopplich** [comment] 2024-05-12 14:24
Sorry, but I can't reproduce this. The page composable is compiled by Vite anyway, I believe there is no difference between browsers. Can you please provide some more information like error logs, screenshots and environment setup?

Seems like you have deleted the `kirbyStatic` prefetch query in your `nuxt.config.ts`. Please make sure to add it or just delete the `useKirbyStaticData` composable if you don't need it. (The import as well, of course.)

This composable is just an example for prefetched data from Kirby at build-time (opposite to everything else like the site data, which is fetched at runtime).

**Comment by johannschopplich** [comment] 2024-05-13 13:55
Closing this as my last comment should give enough information to fix the issue. If you still run into an error, please open a separate issue, including a reproduction and detailed error information. Thanks!

**Closed as not planned by johannschopplich** 2024-05-13 13:55 UTC

**Comment by antoine3000** [comment] 2024-05-17 07:20
thanks!
